### ISSUE TITLE
Error when i use the example code

### ISSUE THREAD

**Issue by bjwelker** [Apollon77/meross-cloud#8]
When i run the example with my Login everything first working but after listung the device i get this error.
```

C:\GitHub\meross-cloud\index.js:252
            this.emit('close', error.toString());
                                     ^

TypeError: Cannot read property 'toString' of undefined
    at MqttClient.client.on (C:\GitHub\meross-cloud\index.js:252:38)
    at MqttClient.emit (events.js:194:15)
    at TLSSocket.f (C:\GitHub\meross-cloud\node_modules\once\once.js:25:25)
    at TLSSocket.onfinish (C:\GitHub\meross-cloud\node_modules\end-of-stream\index.js:30:27)
    at TLSSocket.emit (events.js:189:13)
    at finishMaybe (_stream_writable.js:641:14)
    at stream._final (_stream_writable.js:619:5)
    at TLSSocket.Socket._final (net.js:353:12)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
Bevor 
toggle ...
Toggle Response: err: null, res: {}
18082252723415290 data: "Appliance.Control.ToggleX"
DEV: 18082252723415290 Appliance.Control.ToggleX - data: {"togglex":{"channel":1,"onoff":1,"lmTime":1551183878}}
18082252723415290 reconnected
DEV: 18082252723415290 reconnected
18082252723415290 connected
DEV: 18082252723415290 connected

**Comment by Apollon77** [comment]
fixed in 1.0.1 on npm now
